### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by WwYyFan** [maverickjoy/pepper-tic-tac-toe#1]
I encountered an error when I ran app.py,and can you tell me how to fix it?
```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    import qi
  File "/home/efun/pepper_test/src/pynaoqi-python2.7-2.1.4.13-linux64/qi/__init__.py", line 72, in <module>
    from _qi import Application as _Application
ImportError: libqipython.so: cannot open shared object file: No such file or directory
```

**Comment by maverickjoy** [comment]
You need to install pepper's python sdk `naoqi`. One can downaload it from softbanks website.
If you are working on mac can refer to this **`https://github.com/maverickjoy/pepper-nao-python-installation-mac`**

**Comment by WwYyFan** [comment]
@maverickjoy 
    Thanks for reply,I am using ubuntu16.04,and I have installed pepper's python sdk according to [this tutorial](http://doc.aldebaran.com/2-4/dev/python/install_guide.html).But the error messages still exists.

**Comment by maverickjoy** [comment]
Just check version compatibility as well it should be in your default lets say python 2.7 site packages

For check just just run python on commandline and then try 
import naoqi

If it gives error then that means its not installed properly.

For perfect run it should look like this :

![screenshot from 2018-12-21 15-15-24](https://user-images.githubusercontent.com/11170508/50336160-68b9f880-0533-11e9-8d8c-17d67eba1a7a.png)

**Comment by WwYyFan** [comment]
Is this correct？
![2018-12-21 17-54-24](https://user-images.githubusercontent.com/21033648/50336614-85f9c180-0549-11e9-989a-6ab7ce13d358.png)
![2018-12-21 17-54-39](https://user-images.githubusercontent.com/21033648/50336621-898d4880-0549-11e9-8604-ddfb93f3f15a.png)

**Comment by maverickjoy** [comment]
Yeah, this seems to be fine did you try `import naoqi` after that ? 

If not working try this while exporting PYTHON environmental variable.
```
/pynaoqi/lib/python2.7/site-packages
```
