### ISSUE TITLE
IP

### ISSUE THREAD

**Issue by kbwaaablya** [maverickjoy/pepper-tic-tac-toe#3]
Hello, what is "IP Address of the node in which you are running this program"?(NODE_IP) and how to correctly set it up. Is it PC's current IP in network? And what is DL_SERVER_URL, is it set by default and should not be changed?

**Comment by kbwaaablya** [comment]
One more question is what is tic_tac_toe.top I need to put in home/nao/chat directory and where to get it? I get an error 
```
Traceback (most recent call last):
  File "/home/makscizi/Tic/app.py", line 1310, in <module>
    event_watcher.run()
  File "/home/makscizi/Tic/app.py", line 1274, in run
    self._addTopic()
  File "/home/makscizi/Tic/app.py", line 1230, in _addTopic
    topf_path.encode('utf-8'))
RuntimeError: 	LoadTopic::ALDialog
	Incorrect file /home/nao/chat/tic_tac_toe.top
```
seems that this file is missing from my robot ( it is obvious ).  Where do i get it to put in in the robot?

**Comment by kbwaaablya** [comment]
I just found in the project, facepalm

**Comment by kbwaaablya** [comment]
Can you guide me through with those IPs how to get toss played on pepper tablet, please?
And I still would like to know what are those IP, as I also get this error
```
Error Found on connecting to server : HTTPConnectionPool(host='10.9.42.46', port=5000): Max retries exceeded with url: /getPredictions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecccffa950>: Failed to establish a new connection: [Errno 110] Connection timed out',))

```

**Comment by kbwaaablya** [comment]
As soon as possible, please answear. What is the purpose of that DL server and Node_IP, how to correctly set them, because Robot sends board to DL server and cant connect, so the server is down, what should be done, to get him work?

**Comment by kbwaaablya** [comment]
Hello!
So, as I understood, DL servers are YOLO something, can you give me guidelines for that and how to work with that, as well as your yolo_weights, please?
Respectfully, Maxime.
